image: 'ruby:2.3.1'

cache:
  paths:
    - .bundle
    - vendor/
  key: "bd69e513f60abf9ee7f297baefb9f4ef"

before_script:
  - gem install bundler --no-ri --no-rdoc
  - RAILS_ENV=test bundle install --path vendor/

stages:
  - linting
  - code_analysis
  - testing
  - deployment

code_analysis_job:
  stage: code_analysis
  script:
    - bin/code-analyzers

linting_job:
  stage: linting
  script:
    - bin/linters

test_job:
  stage: testing
  script:
    - bin/test

deployment_job:
  stage: deployment
  script:
    - bin/deploy
  only:
    - master
